@url = http://localhost:4001/county
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI0NDdmYS1jNWJmLTQzNTktYmEwYS00OTE1YzhiODIwZjIiLCJlbWFpbCI6InBoYW50b204NTI2QGR1Y2suY29tIiwicm9sZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3NTIxODEzNDgsImV4cCI6MTc1MjIyNDU0OH0.mJ4_gNy0fql9vgh_hEuDdXK_iFzW_WYoSuxkE6gLjcY

###
GET {{url}}