version: '3.8'
services:
  postgres:
    image: postgres
    container_name: pg-compose-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP
    restart: always


volumes:
  pgdata:
