@url=http://localhost:4001/users

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2RkNTFhMy0zMTVhLTQwNDEtOTNjYy1iMmI2MzljNDFkNTAiLCJlbWFpbCI6InBoYW50b204NTI2QGR1Y2suY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzUxMjcyMTUxLCJleHAiOjE3NTEyNzMzNTF9.pI0xzfBR7VcDPl4a_wWa2WarKj2RckjBJE3ZCJGkvsI
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2RkNTFhMy0zMTVhLTQwNDEtOTNjYy1iMmI2MzljNDFkNTAiLCJlbWFpbCI6InBoYW50b204NTI2QGR1Y2suY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzUxMjAxMzE1LCJleHAiOjE3NTEyMDQ5MTV9.VeD3dRGWE7orQpsHto6CvEr1F-jk-mYLiKSL5Ar9TFw
###
GET {{url}}
Authorization: Bearer {{accessToken}}