@url=http://localhost:4001/users

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI0NDdmYS1jNWJmLTQzNTktYmEwYS00OTE1YzhiODIwZjIiLCJlbWFpbCI6InBoYW50b204NTI2QGR1Y2suY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzUxNTMwNjg5LCJleHAiOjE3NTE1NzM4ODl9.-G9fhrAv2_O_3Ufxds3g8eEp9lrClgvHhFTC7cmA088
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2RkNTFhMy0zMTVhLTQwNDEtOTNjYy1iMmI2MzljNDFkNTAiLCJlbWFpbCI6InBoYW50b204NTI2QGR1Y2suY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzUxMjAxMzE1LCJleHAiOjE3NTEyMDQ5MTV9.VeD3dRGWE7orQpsHto6CvEr1F-jk-mYLiKSL5Ar9TFw
###
GET {{url}}?customers=true
Authorization: Bearer {{accessToken}}
###
GET {{url}}
Authorization: Bearer {{accessToken}}