@url=http://localhost:3000/auth

###
POST {{url}}/login
Content-Type: application/json

{
  "email":"phantom8526@duck.com",
  "password":"123456"
}


###
POST  {{url}}/register
Content-Type: application/json

{
  "username":"phantom",
  "email":"phantom8526@duck.com",
  "phone":"0748200233",
  "password":"123456"
}