@url=http://localhost:4001/auth

###
POST {{url}}/login
Content-Type: application/json

{
  "email":"phantom8526@duck.com",
  "password":"123456"
}


###
POST  {{url}}/register
Content-Type: application/json

{
  "username":"phantom",
  "email":"phantom8526@duck.com",
  "phone":"0748200233",
  "password":"123456"
}


###
GET {{url}}/refresh/fcdd51a3-315a-4041-93cc-b2b639c41d50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2RkNTFhMy0zMTVhLTQwNDEtOTNjYy1iMmI2MzljNDFkNTAiLCJlbWFpbCI6InBoYW50b204NTI2QGR1Y2suY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzUxMjcyOTI3LCJleHAiOjE3NTEyNzY1Mjd9.KYjLzGm9VGuCyfnjfzCaUFLQOZRI01KsPcEoaPMHioI
